services:
  testmoodle:
    build: .
    ports:
      - "8888:80"
    volumes:
      - ./libreria-moodle:/root/libreria-moodle
    stdin_open: true
    tty: true

  testmoodle-restore:
    build: .
    ports:
      - "8888:80"
    volumes:
      - ./libreria-moodle:/root/libreria-moodle
      - ./backup:/root/backup
    stdin_open: true
    tty: true
    command: ["bash", "-c", "./install-from-backup.sh && echo 'Started.' && sleep infinity"]
